CREATE DATABASE IF NOT EXISTS test;
USE test;

CREATE TABLE courses(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title TEXT NOT NULL,
	description TEXT NOT NULL,
	profesor TEXT NOT NULL,
	price DECIMAL(14, 3) NOT NULL
);

CREATE TABLE IF NOT EXISTS profesors(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	date_insert DATE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	date_insert DATE NOT NULL DEFAULT NOW(),
	ammount DECIMAL(14, 3) NOT NULL,
	course TEXT NOT NULL,
	profesor TEXT NOT NULL,
	tax DECIMAL(14, 3) NOT NULL
);

